sudo: required
language: bash
# services:
# - docker

# install: true

git:
  depth: 


env:
  global:
    - PKG_CONFIG_PATH=$HOME/protobuf-$PROTOBUF_VERSION-bin/lib/pkgconfig

install:
- wget https://github.com/protocolbuffers/protobuf/releases/download/v3.8.0/protobuf-cpp-3.8.0.tar.gz
- tar -xzvf protobuf-cpp-3.8.0.tar.gz
- ( cd protobuf-cpp-3.8.0 && ./autogen.sh && ./configure --prefix=$HOME/protobuf-cpp-3.8.0-bin && make -j2 && make install )

# before_script:
# - docker run --rm --privileged multiarch/qemu-user-static:register --reset

script:
- ./autogen.sh
- echo DONE
- make clean
- make
# - docker run --name travis -it hyped/hyped-2018:latest uname -a
# - docker cp . travis:/test/
# - docker commit travis hyped/current
# - docker run -it hyped/current make -j --silent clean hyped

# notifications:
#   slack:
#     rooms:
#         - hypedunlimited:gEtbY2l7hNP2rwgfelMxr6j1#tech-software-repo
   
   
   